apiVersion: v1
items:
  - apiVersion: camel.apache.org/v1alpha1
    kind: IntegrationPlatform
    metadata:
      labels:
        app: camel-k
      name: camel-k
    spec:
      build:
        buildStrategy: pod
        camelVersion: 3.0.0-RC1
        runtimeVersion: 1.0.2-SNAPSHOT
      configuration:
        - type: repository
          value: https://repository.apache.org/content/groups/snapshots@id=apache@snapshots@noreleases
        - type: repository
          value: https://oss.sonatype.org/content/repositories/snapshots/@id=oss@snapshots@noreleases
      profile: Knative
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
